name: REPOSITORY
description: SUBMIT A REPOSITORY UPDATE REQUEST!!!!!
title: "🗃️ [REP]: "
body:
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: |
        ###### THANK YOU FOR TAKING THE TIME TO FILL OUT THIS REPOSITORY UPDATE REQUEST FORM!!!!!
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: description
    attributes:
      label: |
        DESCRIPTION
      description: |
        ###### KINDLY PROVIDE THE DETAILED INFORMATION OF WHAT NEEDS TO BE UPDATED IN THE REPOSITORY!!!!!
      placeholder: |
        DESCRIBE THE UPDATE IN DETAIL.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: input
    id: descsep
    attributes:
      label: |
        --- (TO BE REMOVED AFTER SUBMITTING THE FORM)
      description: |
        ###### THIS WILL BE USED AS A SEPARATOR IN THE MARKDOWN.
        ***KINDLY IGNORE THIS AND DO NOT CHANGE THE VALUE.***
      value: |
        ---
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
