name: Issue Opened Action
description: This action will run when an Issue is Opened.
author: LFD Systems
# Define your inputs here.
inputs:
  github_token:
    description: The GitHub repository token.
    default: GITHUB_TOKEN
    required: true

runs:
  using: node20
  main: dist/index.js
